%{
#include <stdio.h>
#include <stdlib.h>

int vowel = 0;
int consonant = 0;
%}

%%
[aeiouAEIOU] { vowel++; }
[a-zA-Z]    { consonant++; }
[0-9]       ;  // Ignore digits (do nothing).
.           ;  // Ignore any other character (do nothing).
%%

int main()
{
    int numFiles;
    printf("Enter the number of files to process: ");
    scanf("%d", &numFiles);

    printf("Enter the names of %d files:\n", numFiles);

    for (int i = 0; i < numFiles; i++) {
        char fileName[100];
        scanf("%s", fileName);

        FILE *file = fopen(fileName, "r");
        if (!file) {
            fprintf(stderr, "Error opening %s\n", fileName);
            exit(1);
        }

        yyin = file;

        vowel = 0;
        consonant = 0;

        yylex(); // This function is generated by Flex and scans the input according to the specified rules.

        printf("Counts for file %d (%s):\n", i + 1, fileName);
        printf("Number of vowels: %d\n", vowel);
        printf("Number of consonants: %d\n",consonant);

        fclose(file);
    }

    return 0;
}
